### PR TITLE
LPD-30222

### PR DESCRIPTION
**Pull request by javalosjr96**
Testing Solution

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:upgrade

**Comment by javalosjr96** [comment]
ci:stop

**Comment by javalosjr96** [comment]
ci:test:db-partition

**Comment by marianoalvarosaiz** [comment]
From a functional point of view, looks correct, but we should probably look for a final solution, like including portalInstancesLocalService.initializePortalInstance inside the company local service.

Before that I have some doubts:

- Before your changes what is the default execution order of AddDefaultLayoutInitialRequestPortalInstanceLifecycleListener and PortalInstanceLocalService in?
    - Executing the headless service with DB Partition.
    - Executing the headless service without DB Partition
 - After your changes what is the default execution order for those two cases?

**Comment by javalosjr96** [comment]
@marianoalvarosaiz 
Hi,
I did dive into including initializePortalInstance, however this at the moment creates a circular dependency.  

Let me run the test for the second point you mentioned.

**Comment by javalosjr96** [comment]
@marianoalvarosaiz 
Closing and continue the discussion on:
https://github.com/liferay-database-infra/liferay-portal/pull/2204

**Pull request closed without merging**
