### PR TITLE
LPD-18248 Indexes are re-add and duplicate index errors are thrown.

### PR DESCRIPTION
**Pull request by javalosjr96**
Issue:
When re-attempting an upgrade, the indexes are re-added and fail due to them already existing. 
The issue is how we parse the input stream.  

When bundles are added, the SQL files are passed in by a URI that when read, uses StreamUtil.toString.  
This method uses carriage returns(\r\n) instead of new lines(\n\n) when separating the sets of indexes so the delimiter use to create the array does not work.  The other indexes "leak" into the array and get run without being validated since the table name of the first index in the sql file is used. 

Solution:
Match how we parse the input stream in bundles for portal and update the delimiter.

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:upgrade

**Comment by marianoalvarosaiz** [comment]
I'm taking a look.

**Comment by javalosjr96** [comment]
There's multiple failures.

**Comment by marianoalvarosaiz** [comment]
Yes, it's using only the windows separator. I'm performing some tests over some additional changes made. As soon as I finish I'll let you know.

**Comment by javalosjr96** [comment]
@marianoalvarosaiz 
I just made the change to the how the bundle's get the stream read.

**Comment by javalosjr96** [comment]
I'll do a force push to show the changes.

**Comment by javalosjr96** [comment]
ci:test:upgrade

**Comment by javalosjr96** [comment]
@marianoalvarosaiz 
Tests look good with the recent change. 

Ill pull that test you create and restart the PR.

Thanks for writing it!

**Comment by javalosjr96** [comment]
ci:report:2548192670

**Pull request closed without merging**
