### PR TITLE
Do not run initial upgrade processes when the core is not upgraded

### PR DESCRIPTION
**Pull request by achaparro**
Hi @javalosjr96,

After analyzing https://github.com/achaparro/liferay-portal/pull/1050 I think the fix 1 is the best idea because it is better to check if the Core is up to date than checking auto upgrade to false as I suggested in the ticket since we impact only this use case that requires the Core to be upgraded. Good job!

Please, take into account, I moved the check to the register initialization logic for two reasons:
- To only affect modules that have this problem
- We always need to load the upgrade infos since customers can check them via Gogo shell and execute them manually. It is ok to execute them manually now since they won't be able to run the _registerInitialization_ upgrade which is the problematic path.

Verify the pull and let me know if I missed something.

Can you also add a test in [AutoUpgradeProcessTest](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal/portal-upgrade-test/src/testIntegration/java/com/liferay/portal/upgrade/test/AutoUpgradeProcessTest.java) and resend to uniform repo? You can use [this class](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal/portal-upgrade-test/src/testIntegration/java/com/liferay/portal/upgrade/test/AutoUpgradeProcessTest.java#L120) and modify the schema version for the Core release record temporarily to simulate the scenario.

Let me know if you need anything from my side.

Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Hey @javalosjr96, ignore the SF errors, I will fix them when you send the pull to uniform.

**Comment by javalosjr96** [comment]
@achaparro 
I attempted to place the fix in that same spot, but it failed stable testing on CI,  I couldn't reproduce the issue locally.

**Comment by javalosjr96** [comment]
Perhaps it was a fluky test.  I'll verify the results for the PR.

**Comment by achaparro** [comment]
You are right @javalosjr96, I haven't reproduce it locally but I guess we may need to close the connection.

I also fixed the issue with SF in the SF module :-)

**Comment by achaparro** [comment]
https://github.com/javalosjr96/liferay-portal/pull/94

**Pull request closed without merging**
