### PR TITLE
LPS-174140 Do not run initial upgrade processes when the core is not upgraded

### PR DESCRIPTION
**Pull request by achaparro**
- LPS-174140 Prevent the portal from creating _release entries here. This is similiar to the initial solution of using the database auto upgrade.  If the portal is not the latest schema version, it will not create the release_ entries. I did have to use DataAccess becuase the global variable connection is null.
- LPS-174140 Do it in the right place. We have to load the upgradeInfos just in case the user wants to execute them manually. Also, it makes total sense to not load the initialization upgrade step for installations that have pending Core upgrade since that means that they are old installations
- LPS-174140 Modify SF to not check Upgrade connections when the class does not extend any class
- LPS-174140 No longer needed
- LPS-174140 We must close the connection

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Looks better @javalosjr96. The errors may be related to the SF or the rest of the code in the pull.

Please add the test and send to uniform.

Thanks!

**Comment by javalosjr96** [comment]
OK.

**Pull request closed without merging**
